language: go

go: "1.10"

env:
  global:
  - DEP_VERSION="0.4.1"
  - BIN_DIR=$HOME/bin

cache:
  directories:
  - $GOPATH/pkg/dep

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o ${BIN_DIR}/dep
- chmod +x ${BIN_DIR}/dep
- export PATH=$BIN_DIR:$PATH
- go get -u golang.org/x/lint/golint

install:
- make setup

script:
- make lint
- make test
- make
